author = Artur Tarassow
email = atecon@posteo.de
version = 0.1
date = 2022-04-10
description = Event data analysis & Kaplan-Meier estimator
tags = C14 C41
min-version = 2022a
public = kaplanmeier print_kaplanmeier plot_kaplanmeier
help = survival_help.txt
sample-script = survival_sample.inp
data-files = gehan.gdt
